### ISSUE TITLE
Make a button where background changes on  hover.

### ISSUE THREAD

**Issue by roshanlimbu** [roshanlimbu/HacktoberFest_2023#15]
Create a new folder in html & css and code in that directory.

**Comment by gulatikeshav** [comment]
@roshanlimbu  please assign this task to me

**Comment by roshanlimbu** [comment]
> @roshanlimbu please assign this task to me

Assigned

**Comment by Shreshth-Srivastava** [comment]
@roshanlimbu 
Hey there, please assign this issue to me.

**Comment by roshanlimbu** [comment]
> @roshanlimbu Hey there, please assign this issue to me.

Assigned

**Comment by Shreshth-Srivastava** [comment]
@roshanlimbu 
Hey there, I have created a pull request for this issue, please review it.
