### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by braindigitalis** [roshanlimbu/HacktoberFest_2023#59]
https://github.com/roshanlimbu/HacktoberFest_2023/blob/8d564b3fb35e8595f4406545363e87de12e1a189/CPP/Intro%20to%20OOPs/Objects_using_pointers.cpp#L22

**Comment by braindigitalis** [comment]
wait... how is this completed?
nobody fixed the leak!

**Comment by roshanlimbu** [comment]
> wait... how is this completed? nobody fixed the leak!

fixed I guess. Check out.
